// Objective-C API for talking to github.com/Pickleboyonline/ESBuildMobile/lib/esbuildmobile Go package.
//   gobind -lang=objc github.com/Pickleboyonline/ESBuildMobile/lib/esbuildmobile
//
// File is generated by gobind. Do not edit.

#ifndef __Esbuildmobile_H__
#define __Esbuildmobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class EsbuildmobileBuildOptions;
@class EsbuildmobileTransformOptions;

@interface EsbuildmobileBuildOptions : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewBuildOptions returns BuildOptions with defaults
 */
- (nullable instancetype)init;
@property (nonatomic) BOOL bundle;
@property (nonatomic) BOOL write;
@property (nonatomic) NSString* _Nonnull outfile;
// skipped field BuildOptions.Platform with unsupported type: github.com/evanw/esbuild/pkg/api.Platform

// skipped field BuildOptions.Format with unsupported type: github.com/evanw/esbuild/pkg/api.Format

// skipped field BuildOptions.Target with unsupported type: github.com/evanw/esbuild/pkg/api.Target

// skipped field BuildOptions.Sourcemap with unsupported type: github.com/evanw/esbuild/pkg/api.SourceMap

@property (nonatomic) BOOL minifyWhitespace;
@property (nonatomic) BOOL minifyIdentifiers;
@property (nonatomic) BOOL minifySyntax;
@property (nonatomic) NSString* _Nonnull globalName;
// skipped field BuildOptions.Define with unsupported type: map[string]string

// skipped field BuildOptions.LogLevel with unsupported type: github.com/evanw/esbuild/pkg/api.LogLevel

@property (nonatomic) long logLimit;
// skipped field BuildOptions.Loader with unsupported type: github.com/evanw/esbuild/pkg/api.Loader

@property (nonatomic) NSString* _Nonnull sourcefile;
- (void)configureBundle:(BOOL)bundle;
- (void)configureDefineEntry:(NSString* _Nullable)key value:(NSString* _Nullable)value;
// skipped method BuildOptions.ConfigureFormat with unsupported parameter or return types

- (void)configureFormatByString:(NSString* _Nullable)format;
- (void)configureGlobalName:(NSString* _Nullable)n;
// skipped method BuildOptions.ConfigureLoader with unsupported parameter or return types

- (void)configureLoaderByString:(NSString* _Nullable)loader;
// skipped method BuildOptions.ConfigureLogLevel with unsupported parameter or return types

- (void)configureLogLevelByString:(NSString* _Nullable)level;
- (void)configureLogLimit:(long)l;
- (void)configureMinifyIdentifiers:(BOOL)v;
- (void)configureMinifySyntax:(BOOL)v;
- (void)configureMinifyWhitespace:(BOOL)v;
- (void)configureOutfile:(NSString* _Nullable)outfile;
// skipped method BuildOptions.ConfigurePlatform with unsupported parameter or return types

/**
 * Helper config methods using string values for gomobile compatibility
 */
- (void)configurePlatformByString:(NSString* _Nullable)platform;
- (void)configureSourcefile:(NSString* _Nullable)sf;
// skipped method BuildOptions.ConfigureSourcemap with unsupported parameter or return types

- (void)configureSourcemapByString:(NSString* _Nullable)sm;
// skipped method BuildOptions.ConfigureTarget with unsupported parameter or return types

- (void)configureTargetByString:(NSString* _Nullable)target;
- (void)configureWrite:(BOOL)write;
@end

@interface EsbuildmobileTransformOptions : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewTransformOptions creates a new TransformOptions with default values
 */
- (nullable instancetype)init;
// skipped field TransformOptions.Color with unsupported type: github.com/evanw/esbuild/pkg/api.StderrColor

// skipped field TransformOptions.LogLevel with unsupported type: github.com/evanw/esbuild/pkg/api.LogLevel

@property (nonatomic) long logLimit;
// skipped field TransformOptions.LogOverride with unsupported type: map[string]github.com/evanw/esbuild/pkg/api.LogLevel

// skipped field TransformOptions.Sourcemap with unsupported type: github.com/evanw/esbuild/pkg/api.SourceMap

@property (nonatomic) NSString* _Nonnull sourceRoot;
// skipped field TransformOptions.SourcesContent with unsupported type: github.com/evanw/esbuild/pkg/api.SourcesContent

// skipped field TransformOptions.Target with unsupported type: github.com/evanw/esbuild/pkg/api.Target

// skipped field TransformOptions.Engines with unsupported type: []github.com/evanw/esbuild/pkg/api.Engine

// skipped field TransformOptions.Supported with unsupported type: map[string]bool

// skipped field TransformOptions.Platform with unsupported type: github.com/evanw/esbuild/pkg/api.Platform

// skipped field TransformOptions.Format with unsupported type: github.com/evanw/esbuild/pkg/api.Format

@property (nonatomic) NSString* _Nonnull globalName;
@property (nonatomic) NSString* _Nonnull mangleProps;
@property (nonatomic) NSString* _Nonnull reserveProps;
// skipped field TransformOptions.MangleQuoted with unsupported type: github.com/evanw/esbuild/pkg/api.MangleQuoted

// skipped field TransformOptions.MangleCache with unsupported type: map[string]interface{}

// skipped field TransformOptions.Drop with unsupported type: github.com/evanw/esbuild/pkg/api.Drop

// skipped field TransformOptions.DropLabels with unsupported type: []string

@property (nonatomic) BOOL minifyWhitespace;
@property (nonatomic) BOOL minifyIdentifiers;
@property (nonatomic) BOOL minifySyntax;
@property (nonatomic) long lineLimit;
// skipped field TransformOptions.Charset with unsupported type: github.com/evanw/esbuild/pkg/api.Charset

// skipped field TransformOptions.TreeShaking with unsupported type: github.com/evanw/esbuild/pkg/api.TreeShaking

@property (nonatomic) BOOL ignoreAnnotations;
// skipped field TransformOptions.LegalComments with unsupported type: github.com/evanw/esbuild/pkg/api.LegalComments

// skipped field TransformOptions.JSX with unsupported type: github.com/evanw/esbuild/pkg/api.JSX

@property (nonatomic) NSString* _Nonnull jsxFactory;
@property (nonatomic) NSString* _Nonnull jsxFragment;
@property (nonatomic) NSString* _Nonnull jsxImportSource;
@property (nonatomic) BOOL jsxDev;
@property (nonatomic) BOOL jsxSideEffects;
@property (nonatomic) NSString* _Nonnull tsconfigRaw;
@property (nonatomic) NSString* _Nonnull banner;
@property (nonatomic) NSString* _Nonnull footer;
// skipped field TransformOptions.Define with unsupported type: map[string]string

// skipped field TransformOptions.Pure with unsupported type: []string

@property (nonatomic) BOOL keepNames;
@property (nonatomic) NSString* _Nonnull sourcefile;
// skipped field TransformOptions.Loader with unsupported type: github.com/evanw/esbuild/pkg/api.Loader

/**
 * Configure banner text
 */
- (void)configureBanner:(NSString* _Nullable)banner;
// skipped method TransformOptions.ConfigureCharset with unsupported parameter or return types

/**
 * Configure charset by string
 */
- (void)configureCharsetByString:(NSString* _Nullable)charset;
// skipped method TransformOptions.ConfigureColor with unsupported parameter or return types

/**
 * Configure color by string
 */
- (void)configureColorByString:(NSString* _Nullable)color;
// skipped method TransformOptions.ConfigureDefine with unsupported parameter or return types

/**
 * Configure define by key-value pairs
 */
- (void)configureDefineEntry:(NSString* _Nullable)key value:(NSString* _Nullable)value;
// skipped method TransformOptions.ConfigureDrop with unsupported parameter or return types

/**
 * Configure drop by string
 */
- (void)configureDropByString:(NSString* _Nullable)drop;
// skipped method TransformOptions.ConfigureDropLabels with unsupported parameter or return types

// skipped method TransformOptions.ConfigureDropLabelsBySlice with unsupported parameter or return types

// skipped method TransformOptions.ConfigureEngines with unsupported parameter or return types

/**
 * Configure footer text
 */
- (void)configureFooter:(NSString* _Nullable)footer;
// skipped method TransformOptions.ConfigureFormat with unsupported parameter or return types

/**
 * Configure format by string
 */
- (void)configureFormatByString:(NSString* _Nullable)format;
/**
 * Configure global name for UMD bundles
 */
- (void)configureGlobalName:(NSString* _Nullable)name;
/**
 * Configure ignore annotations
 */
- (void)configureIgnoreAnnotations:(BOOL)enabled;
// skipped method TransformOptions.ConfigureJSX with unsupported parameter or return types

/**
 * Configure JSX mode by string
 */
- (void)configureJSXByString:(NSString* _Nullable)jsx;
/**
 * Configure JSX development mode
 */
- (void)configureJSXDev:(BOOL)enabled;
/**
 * Change `React.createElement` to custom name
 */
- (void)configureJSXFactory:(NSString* _Nullable)factoryName;
/**
 * Change `React.Fragment` to custom name
 */
- (void)configureJSXFragment:(NSString* _Nullable)fragmentName;
/**
 * Configure JSX import source
 */
- (void)configureJSXImportSource:(NSString* _Nullable)importSource;
/**
 * Configure JSX side effects
 */
- (void)configureJSXSideEffects:(BOOL)enabled;
/**
 * Configure keep names option
 */
- (void)configureKeepNames:(BOOL)enabled;
// skipped method TransformOptions.ConfigureLegalComments with unsupported parameter or return types

/**
 * Configure legal comments by string
 */
- (void)configureLegalCommentsByString:(NSString* _Nullable)comments;
/**
 * Configure line limit
 */
- (void)configureLineLimit:(long)limit;
// skipped method TransformOptions.ConfigureLoader with unsupported parameter or return types

/**
 * Configure loader by string
 */
- (void)configureLoaderByString:(NSString* _Nullable)loader;
// skipped method TransformOptions.ConfigureLogLevel with unsupported parameter or return types

/**
 * Configure log level by string
 */
- (void)configureLogLevelByString:(NSString* _Nullable)level;
/**
 * Configure log limit
 */
- (void)configureLogLimit:(long)limit;
// skipped method TransformOptions.ConfigureLogOverride with unsupported parameter or return types

// skipped method TransformOptions.ConfigureMangleCache with unsupported parameter or return types

/**
 * Configure mangle properties pattern
 */
- (void)configureMangleProps:(NSString* _Nullable)pattern;
// skipped method TransformOptions.ConfigureMangleQuoted with unsupported parameter or return types

/**
 * Configure mangle quoted by string
 */
- (void)configureMangleQuotedByString:(NSString* _Nullable)quoted;
/**
 * Configure identifier minification
 */
- (void)configureMinifyIdentifiers:(BOOL)enabled;
/**
 * Configure syntax minification
 */
- (void)configureMinifySyntax:(BOOL)enabled;
/**
 * Configure whitespace minification
 */
- (void)configureMinifyWhitespace:(BOOL)enabled;
// skipped method TransformOptions.ConfigurePlatform with unsupported parameter or return types

/**
 * Configure platform by string
 */
- (void)configurePlatformByString:(NSString* _Nullable)platform;
// skipped method TransformOptions.ConfigurePure with unsupported parameter or return types

// skipped method TransformOptions.ConfigurePureBySlice with unsupported parameter or return types

/**
 * Configure reserve properties pattern
 */
- (void)configureReserveProps:(NSString* _Nullable)pattern;
/**
 * Configure source root directory
 */
- (void)configureSourceRoot:(NSString* _Nullable)root;
/**
 * Configure source file name
 */
- (void)configureSourcefile:(NSString* _Nullable)filename;
// skipped method TransformOptions.ConfigureSourcemap with unsupported parameter or return types

/**
 * Configure sourcemap by string
 */
- (void)configureSourcemapByString:(NSString* _Nullable)sourcemap;
// skipped method TransformOptions.ConfigureSourcesContent with unsupported parameter or return types

/**
 * Configure sources content by string
 */
- (void)configureSourcesContentByString:(NSString* _Nullable)content;
// skipped method TransformOptions.ConfigureSupported with unsupported parameter or return types

/**
 * Configure supported feature
 */
- (void)configureSupportedFeature:(NSString* _Nullable)feature supported:(BOOL)supported;
// skipped method TransformOptions.ConfigureTarget with unsupported parameter or return types

/**
 * Configure target by string
 */
- (void)configureTargetByString:(NSString* _Nullable)target;
// skipped method TransformOptions.ConfigureTreeShaking with unsupported parameter or return types

/**
 * Configure tree shaking by string
 */
- (void)configureTreeShakingByString:(NSString* _Nullable)shaking;
/**
 * Configure raw tsconfig content
 */
- (void)configureTsconfigRaw:(NSString* _Nullable)config;
/**
 * WithJSXFactory sets the JSX factory function name (e.g., "React.createElement")
 */
- (void)withJSXFactory:(NSString* _Nullable)factoryName;
/**
 * WithJSXFragment sets the JSX fragment function name (e.g., "React.Fragment")
 */
- (void)withJSXFragment:(NSString* _Nullable)fragmentName;
@end

/**
 * Build compiles JavaScript using esbuild's build API with stdin.
Returns the bundled code as a string if Write is false.
`BuildOptions` is optional.
 */
FOUNDATION_EXPORT NSString* _Nonnull EsbuildmobileBuild(NSString* _Nullable input, EsbuildmobileBuildOptions* _Nullable options, NSError* _Nullable* _Nullable error);

/**
 * NewBuildOptions returns BuildOptions with defaults
 */
FOUNDATION_EXPORT EsbuildmobileBuildOptions* _Nullable EsbuildmobileNewBuildOptions(void);

/**
 * NewTransformOptions creates a new TransformOptions with default values
 */
FOUNDATION_EXPORT EsbuildmobileTransformOptions* _Nullable EsbuildmobileNewTransformOptions(void);

/**
 * Returns code and error
`TransformOptions` is optional
 */
FOUNDATION_EXPORT NSString* _Nonnull EsbuildmobileTransformJSX(NSString* _Nullable input, EsbuildmobileTransformOptions* _Nullable options, NSError* _Nullable* _Nullable error);

#endif
