// Objective-C API for talking to github.com/Pickleboyonline/ESBuildMobile/lib/esbuildmobile Go package.
//   gobind -lang=objc github.com/Pickleboyonline/ESBuildMobile/lib/esbuildmobile
//
// File is generated by gobind. Do not edit.

#ifndef __Esbuildmobile_H__
#define __Esbuildmobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class EsbuildmobileBuildOptions;
@class EsbuildmobileBuildResult;
@class EsbuildmobileEngine;
@class EsbuildmobileOnEndResult;
@class EsbuildmobileOnLoadArgs;
@class EsbuildmobileOnLoadOptions;
@class EsbuildmobileOnLoadResult;
@class EsbuildmobileOnResolveArgs;
@class EsbuildmobileOnResolveOptions;
@class EsbuildmobileOnResolveResult;
@class EsbuildmobileOnStartResult;
@class EsbuildmobilePlugin;
@class EsbuildmobileResolveOptions;
@class EsbuildmobileResolveResult;
@class EsbuildmobileSimpleLoadCallback;
@class EsbuildmobileSimpleOnStartCallback;
@class EsbuildmobileSimpleResolveCallback;
@class EsbuildmobileSwiftOnEndCallback;
@class EsbuildmobileSwiftOnLoadCallback;
@class EsbuildmobileSwiftOnResolveCallback;
@class EsbuildmobileSwiftOnStartCallback;
@class EsbuildmobileTransformOptions;
@protocol EsbuildmobileOnEndCallback;
@class EsbuildmobileOnEndCallback;
@protocol EsbuildmobileOnLoadCallback;
@class EsbuildmobileOnLoadCallback;
@protocol EsbuildmobileOnResolveCallback;
@class EsbuildmobileOnResolveCallback;
@protocol EsbuildmobileOnStartCallback;
@class EsbuildmobileOnStartCallback;

@protocol EsbuildmobileOnEndCallback <NSObject>
- (EsbuildmobileOnEndResult* _Nullable)call:(EsbuildmobileBuildResult* _Nullable)result;
@end

@protocol EsbuildmobileOnLoadCallback <NSObject>
- (EsbuildmobileOnLoadResult* _Nullable)call:(EsbuildmobileOnLoadArgs* _Nullable)args;
@end

@protocol EsbuildmobileOnResolveCallback <NSObject>
- (EsbuildmobileOnResolveResult* _Nullable)call:(EsbuildmobileOnResolveArgs* _Nullable)args;
@end

@protocol EsbuildmobileOnStartCallback <NSObject>
- (EsbuildmobileOnStartResult* _Nullable)call;
@end

@interface EsbuildmobileBuildOptions : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewBuildOptions returns BuildOptions with defaults
 */
- (nullable instancetype)init;
// skipped field BuildOptions.Color with unsupported type: github.com/evanw/esbuild/pkg/api.StderrColor

// skipped field BuildOptions.LogLevel with unsupported type: github.com/evanw/esbuild/pkg/api.LogLevel

@property (nonatomic) long logLimit;
// skipped field BuildOptions.LogOverride with unsupported type: map[string]github.com/evanw/esbuild/pkg/api.LogLevel

// skipped field BuildOptions.Sourcemap with unsupported type: github.com/evanw/esbuild/pkg/api.SourceMap

@property (nonatomic) NSString* _Nonnull sourceRoot;
// skipped field BuildOptions.SourcesContent with unsupported type: github.com/evanw/esbuild/pkg/api.SourcesContent

// skipped field BuildOptions.Target with unsupported type: github.com/evanw/esbuild/pkg/api.Target

// skipped field BuildOptions.Engines with unsupported type: []github.com/evanw/esbuild/pkg/api.Engine

// skipped field BuildOptions.Supported with unsupported type: map[string]bool

/**
 * Minification and mangling options
 */
@property (nonatomic) NSString* _Nonnull mangleProps;
@property (nonatomic) NSString* _Nonnull reserveProps;
// skipped field BuildOptions.MangleQuoted with unsupported type: github.com/evanw/esbuild/pkg/api.MangleQuoted

// skipped field BuildOptions.MangleCache with unsupported type: map[string]interface{}

// skipped field BuildOptions.Drop with unsupported type: github.com/evanw/esbuild/pkg/api.Drop

// skipped field BuildOptions.DropLabels with unsupported type: []string

@property (nonatomic) BOOL minifyWhitespace;
@property (nonatomic) BOOL minifyIdentifiers;
@property (nonatomic) BOOL minifySyntax;
@property (nonatomic) long lineLimit;
// skipped field BuildOptions.Charset with unsupported type: github.com/evanw/esbuild/pkg/api.Charset

// skipped field BuildOptions.TreeShaking with unsupported type: github.com/evanw/esbuild/pkg/api.TreeShaking

@property (nonatomic) BOOL ignoreAnnotations;
// skipped field BuildOptions.LegalComments with unsupported type: github.com/evanw/esbuild/pkg/api.LegalComments

// skipped field BuildOptions.JSX with unsupported type: github.com/evanw/esbuild/pkg/api.JSX

@property (nonatomic) NSString* _Nonnull jsxFactory;
@property (nonatomic) NSString* _Nonnull jsxFragment;
@property (nonatomic) NSString* _Nonnull jsxImportSource;
@property (nonatomic) BOOL jsxDev;
@property (nonatomic) BOOL jsxSideEffects;
// skipped field BuildOptions.Define with unsupported type: map[string]string

// skipped field BuildOptions.Pure with unsupported type: []string

@property (nonatomic) BOOL keepNames;
/**
 * Bundle options
 */
@property (nonatomic) NSString* _Nonnull globalName;
@property (nonatomic) BOOL bundle;
@property (nonatomic) BOOL preserveSymlinks;
@property (nonatomic) BOOL splitting;
@property (nonatomic) NSString* _Nonnull outfile;
@property (nonatomic) BOOL metafile;
@property (nonatomic) NSString* _Nonnull outdir;
@property (nonatomic) NSString* _Nonnull outbase;
@property (nonatomic) NSString* _Nonnull absWorkingDir;
// skipped field BuildOptions.Platform with unsupported type: github.com/evanw/esbuild/pkg/api.Platform

// skipped field BuildOptions.Format with unsupported type: github.com/evanw/esbuild/pkg/api.Format

// skipped field BuildOptions.External with unsupported type: []string

// skipped field BuildOptions.Packages with unsupported type: github.com/evanw/esbuild/pkg/api.Packages

// skipped field BuildOptions.Alias with unsupported type: map[string]string

// skipped field BuildOptions.MainFields with unsupported type: []string

// skipped field BuildOptions.Conditions with unsupported type: []string

// skipped field BuildOptions.Loader with unsupported type: map[string]github.com/evanw/esbuild/pkg/api.Loader

// skipped field BuildOptions.ResolveExtensions with unsupported type: []string

@property (nonatomic) NSString* _Nonnull tsconfig;
@property (nonatomic) NSString* _Nonnull tsconfigRaw;
// skipped field BuildOptions.OutExtension with unsupported type: map[string]string

@property (nonatomic) NSString* _Nonnull publicPath;
// skipped field BuildOptions.Inject with unsupported type: []string

// skipped field BuildOptions.Banner with unsupported type: map[string]string

// skipped field BuildOptions.Footer with unsupported type: map[string]string

// skipped field BuildOptions.NodePaths with unsupported type: []string

/**
 * Output naming options
 */
@property (nonatomic) NSString* _Nonnull entryNames;
@property (nonatomic) NSString* _Nonnull chunkNames;
@property (nonatomic) NSString* _Nonnull assetNames;
// skipped field BuildOptions.EntryPoints with unsupported type: []string

// skipped field BuildOptions.EntryPointsAdvanced with unsupported type: []github.com/evanw/esbuild/pkg/api.EntryPoint

// skipped field BuildOptions.Stdin with unsupported type: *github.com/evanw/esbuild/pkg/api.StdinOptions

@property (nonatomic) BOOL write;
@property (nonatomic) BOOL allowOverwrite;
// skipped field BuildOptions.Plugins with unsupported type: []*github.com/Pickleboyonline/ESBuildMobile/lib/esbuildmobile.Plugin

/**
 * Legacy properties for backwards compatibility
 */
@property (nonatomic) NSString* _Nonnull sourcefile;
// skipped field BuildOptions.LoaderSingle with unsupported type: github.com/evanw/esbuild/pkg/api.Loader

- (void)addAdvancedEntryPoint:(NSString* _Nullable)input output:(NSString* _Nullable)output;
- (void)addCondition:(NSString* _Nullable)condition;
- (void)addDropLabel:(NSString* _Nullable)label;
- (void)addEngine:(NSString* _Nullable)name version:(NSString* _Nullable)version;
/**
 * Array/slice configuration methods
 */
- (void)addEntryPoint:(NSString* _Nullable)path;
- (void)addExternal:(NSString* _Nullable)module;
- (void)addInject:(NSString* _Nullable)file;
- (void)addMainField:(NSString* _Nullable)field;
- (void)addNodePath:(NSString* _Nullable)path;
- (void)addPlugin:(EsbuildmobilePlugin* _Nullable)plugin;
- (void)addPure:(NSString* _Nullable)fn;
- (void)addResolveExtension:(NSString* _Nullable)ext;
- (void)clearAlias;
- (void)clearBanner;
- (void)clearConditions;
- (void)clearDefine;
- (void)clearDropLabels;
- (void)clearEngines;
/**
 * Clear methods for arrays and maps
 */
- (void)clearEntryPoints;
- (void)clearEntryPointsAdvanced;
- (void)clearExternal;
- (void)clearFooter;
- (void)clearInject;
- (void)clearLoader;
- (void)clearLogOverride;
- (void)clearMainFields;
- (void)clearMangleCache;
- (void)clearNodePaths;
- (void)clearOutExtension;
- (void)clearPlugins;
- (void)clearPure;
- (void)clearResolveExtensions;
- (void)clearSupported;
- (void)configureAbsWorkingDir:(NSString* _Nullable)dir;
- (void)configureAliasEntry:(NSString* _Nullable)from to:(NSString* _Nullable)to;
- (void)configureAllowOverwrite:(BOOL)v;
- (void)configureAssetNames:(NSString* _Nullable)names;
- (void)configureBannerEntry:(NSString* _Nullable)fileType banner:(NSString* _Nullable)banner;
/**
 * Basic configuration methods
 */
- (void)configureBundle:(BOOL)bundle;
// skipped method BuildOptions.ConfigureCharset with unsupported parameter or return types

- (void)configureCharsetByString:(NSString* _Nullable)charset;
- (void)configureChunkNames:(NSString* _Nullable)names;
// skipped method BuildOptions.ConfigureColor with unsupported parameter or return types

- (void)configureColorByString:(NSString* _Nullable)color;
/**
 * Map configuration methods
 */
- (void)configureDefineEntry:(NSString* _Nullable)key value:(NSString* _Nullable)value;
// skipped method BuildOptions.ConfigureDrop with unsupported parameter or return types

/**
 * Drop configuration helpers
 */
- (void)configureDropConsole:(BOOL)drop;
- (void)configureDropDebugger:(BOOL)drop;
/**
 * Output naming configuration
 */
- (void)configureEntryNames:(NSString* _Nullable)names;
- (void)configureFooterEntry:(NSString* _Nullable)fileType footer:(NSString* _Nullable)footer;
// skipped method BuildOptions.ConfigureFormat with unsupported parameter or return types

- (void)configureFormatByString:(NSString* _Nullable)format;
- (void)configureGlobalName:(NSString* _Nullable)n;
- (void)configureIgnoreAnnotations:(BOOL)v;
// skipped method BuildOptions.ConfigureJSX with unsupported parameter or return types

- (void)configureJSXByString:(NSString* _Nullable)jsx;
- (void)configureJSXDev:(BOOL)dev;
- (void)configureJSXFactory:(NSString* _Nullable)factory;
- (void)configureJSXFragment:(NSString* _Nullable)fragment;
- (void)configureJSXImportSource:(NSString* _Nullable)source;
- (void)configureJSXSideEffects:(BOOL)effects;
- (void)configureKeepNames:(BOOL)v;
// skipped method BuildOptions.ConfigureLegalComments with unsupported parameter or return types

- (void)configureLegalCommentsByString:(NSString* _Nullable)comments;
- (void)configureLineLimit:(long)limit;
- (void)configureLoaderByString:(NSString* _Nullable)loader;
// skipped method BuildOptions.ConfigureLoaderEntry with unsupported parameter or return types

// skipped method BuildOptions.ConfigureLogLevel with unsupported parameter or return types

- (void)configureLogLevelByString:(NSString* _Nullable)level;
- (void)configureLogLimit:(long)l;
// skipped method BuildOptions.ConfigureLogOverrideEntry with unsupported parameter or return types

/**
 * Mangle configuration
 */
- (void)configureMangleProps:(NSString* _Nullable)props;
// skipped method BuildOptions.ConfigureMangleQuoted with unsupported parameter or return types

- (void)configureMangleQuotedByString:(NSString* _Nullable)quoted;
- (void)configureMetafile:(BOOL)v;
- (void)configureMinifyIdentifiers:(BOOL)v;
- (void)configureMinifySyntax:(BOOL)v;
/**
 * Minification options
 */
- (void)configureMinifyWhitespace:(BOOL)v;
- (void)configureOutExtensionEntry:(NSString* _Nullable)ext newExt:(NSString* _Nullable)newExt;
- (void)configureOutbase:(NSString* _Nullable)outbase;
- (void)configureOutdir:(NSString* _Nullable)outdir;
- (void)configureOutfile:(NSString* _Nullable)outfile;
// skipped method BuildOptions.ConfigurePackages with unsupported parameter or return types

- (void)configurePackagesByString:(NSString* _Nullable)packages;
// skipped method BuildOptions.ConfigurePlatform with unsupported parameter or return types

/**
 * Helper config methods using string values for gomobile compatibility
 */
- (void)configurePlatformByString:(NSString* _Nullable)platform;
/**
 * Advanced bundling options
 */
- (void)configurePreserveSymlinks:(BOOL)v;
- (void)configurePublicPath:(NSString* _Nullable)path;
- (void)configureReserveProps:(NSString* _Nullable)props;
- (void)configureSourceRoot:(NSString* _Nullable)root;
- (void)configureSourcefile:(NSString* _Nullable)sf;
// skipped method BuildOptions.ConfigureSourcemap with unsupported parameter or return types

- (void)configureSourcemapByString:(NSString* _Nullable)sm;
// skipped method BuildOptions.ConfigureSourcesContent with unsupported parameter or return types

- (void)configureSourcesContentByString:(NSString* _Nullable)content;
- (void)configureSplitting:(BOOL)v;
// skipped method BuildOptions.ConfigureStdin with unsupported parameter or return types

- (void)configureStdinByString:(NSString* _Nullable)contents resolveDir:(NSString* _Nullable)resolveDir sourcefile:(NSString* _Nullable)sourcefile loader:(NSString* _Nullable)loader;
- (void)configureSupportedEntry:(NSString* _Nullable)feature supported:(BOOL)supported;
// skipped method BuildOptions.ConfigureTarget with unsupported parameter or return types

- (void)configureTargetByString:(NSString* _Nullable)target;
// skipped method BuildOptions.ConfigureTreeShaking with unsupported parameter or return types

- (void)configureTreeShakingByString:(NSString* _Nullable)treeShaking;
/**
 * TypeScript configuration
 */
- (void)configureTsconfig:(NSString* _Nullable)config;
- (void)configureTsconfigRaw:(NSString* _Nullable)raw;
- (void)configureWrite:(BOOL)write;
/**
 * Methods for EntryPointsAdvanced (complex type)
 */
- (NSString* _Nonnull)getAdvancedEntryPointInput:(long)index;
- (NSString* _Nonnull)getAdvancedEntryPointOutput:(long)index;
- (long)getAliasCount;
// skipped method BuildOptions.GetAliasKeys with unsupported parameter or return types

- (NSString* _Nonnull)getAliasValue:(NSString* _Nullable)key;
- (long)getBannerCount;
// skipped method BuildOptions.GetBannerKeys with unsupported parameter or return types

- (NSString* _Nonnull)getBannerValue:(NSString* _Nullable)key;
- (long)getCharset;
- (long)getColor;
- (NSString* _Nonnull)getCondition:(long)index;
- (long)getConditionsCount;
/**
 * Getter methods for map sizes
 */
- (long)getDefineCount;
// skipped method BuildOptions.GetDefineKeys with unsupported parameter or return types

/**
 * Methods to get values from maps by key
 */
- (NSString* _Nonnull)getDefineValue:(NSString* _Nullable)key;
- (long)getDrop;
- (NSString* _Nonnull)getDropLabel:(long)index;
- (long)getDropLabelsCount;
/**
 * Getter methods for string array elements
 */
- (NSString* _Nonnull)getEntryPoint:(long)index;
- (long)getEntryPointsAdvancedCount;
/**
 * Getter methods for slices and maps (return length/size info)
 */
- (long)getEntryPointsCount;
- (NSString* _Nonnull)getExternal:(long)index;
- (long)getExternalCount;
- (long)getFooterCount;
// skipped method BuildOptions.GetFooterKeys with unsupported parameter or return types

- (NSString* _Nonnull)getFooterValue:(NSString* _Nullable)key;
- (long)getFormat;
- (NSString* _Nonnull)getInject:(long)index;
- (long)getInjectCount;
- (long)getJSX;
- (long)getLegalComments;
- (long)getLoaderCount;
// skipped method BuildOptions.GetLoaderKeys with unsupported parameter or return types

- (long)getLoaderSingle;
- (long)getLoaderValue:(NSString* _Nullable)key;
- (long)getLogLevel;
- (long)getLogOverrideCount;
// skipped method BuildOptions.GetLogOverrideKeys with unsupported parameter or return types

- (long)getLogOverrideValue:(NSString* _Nullable)key;
- (NSString* _Nonnull)getMainField:(long)index;
- (long)getMainFieldsCount;
- (long)getMangleCacheCount;
- (long)getMangleQuoted;
- (NSString* _Nonnull)getNodePath:(long)index;
- (long)getNodePathsCount;
- (long)getOutExtensionCount;
// skipped method BuildOptions.GetOutExtensionKeys with unsupported parameter or return types

- (NSString* _Nonnull)getOutExtensionValue:(NSString* _Nullable)key;
- (long)getPackages;
/**
 * Getter methods for current BuildOptions values
 */
- (long)getPlatform;
- (EsbuildmobilePlugin* _Nullable)getPlugin:(long)index;
- (long)getPluginsCount;
- (NSString* _Nonnull)getPure:(long)index;
- (long)getPureCount;
- (NSString* _Nonnull)getResolveExtension:(long)index;
- (long)getResolveExtensionsCount;
- (long)getSourcemap;
- (long)getSourcesContent;
- (long)getSupportedCount;
// skipped method BuildOptions.GetSupportedKeys with unsupported parameter or return types

- (BOOL)getSupportedValue:(NSString* _Nullable)key;
- (long)getTarget;
- (long)getTreeShaking;
- (void)setCharsetByInt:(long)charset;
- (void)setColorByInt:(long)color;
- (void)setDropByInt:(long)drop;
- (void)setFormatByInt:(long)format;
- (void)setJSXByInt:(long)jsx;
- (void)setLegalCommentsByInt:(long)comments;
- (void)setLoaderSingleByInt:(long)loader;
- (void)setLoaderValueByInt:(NSString* _Nullable)key value:(long)value;
- (void)setLogLevelByInt:(long)logLevel;
/**
 * Methods to set map values by key with integer enum values
 */
- (void)setLogOverrideValueByInt:(NSString* _Nullable)key value:(long)value;
- (void)setMangleQuotedByInt:(long)quoted;
- (void)setPackagesByInt:(long)packages;
/**
 * Set methods using enum values as integers
 */
- (void)setPlatformByInt:(long)platform;
- (void)setSourcemapByInt:(long)sourcemap;
- (void)setSourcesContentByInt:(long)content;
- (void)setTargetByInt:(long)target;
- (void)setTreeShakingByInt:(long)shaking;
// skipped method BuildOptions.ToAPIBuildOptions with unsupported parameter or return types

@end

/**
 * BuildResult represents the result of a build (simplified for mobile)
 */
@interface EsbuildmobileBuildResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field BuildResult.Errors with unsupported type: []github.com/evanw/esbuild/pkg/api.Message

// skipped field BuildResult.Warnings with unsupported type: []github.com/evanw/esbuild/pkg/api.Message

@end

/**
 * Engine represents a JavaScript engine with its version
This is our custom wrapper that maps to esbuild's api.Engine
 */
@interface EsbuildmobileEngine : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field Engine.Name with unsupported type: github.com/evanw/esbuild/pkg/api.EngineName

@property (nonatomic) NSString* _Nonnull version;
// skipped method Engine.ToAPIEngine with unsupported parameter or return types

@end

/**
 * OnEndResult contains the result from an OnEnd callback
 */
@interface EsbuildmobileOnEndResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init;
// skipped field OnEndResult.Errors with unsupported type: []github.com/evanw/esbuild/pkg/api.Message

// skipped field OnEndResult.Warnings with unsupported type: []github.com/evanw/esbuild/pkg/api.Message

@end

/**
 * OnLoadArgs contains arguments passed to the OnLoad callback
 */
@interface EsbuildmobileOnLoadArgs : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull path;
@property (nonatomic) NSString* _Nonnull namespace;
@property (nonatomic) NSString* _Nonnull suffix;
@end

/**
 * OnLoadOptions contains options for the OnLoad callback
 */
@interface EsbuildmobileOnLoadOptions : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init;
@property (nonatomic) NSString* _Nonnull filter;
@property (nonatomic) NSString* _Nonnull namespace;
- (NSString* _Nonnull)getLoadFilter;
- (NSString* _Nonnull)getLoadNamespace;
- (void)setLoadFilter:(NSString* _Nullable)filter;
- (void)setLoadNamespace:(NSString* _Nullable)namespace;
// skipped method OnLoadOptions.ToAPI with unsupported parameter or return types

@end

/**
 * OnLoadResult contains the result from an OnLoad callback
 */
@interface EsbuildmobileOnLoadResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init;
@property (nonatomic) NSString* _Nonnull pluginName;
// skipped field OnLoadResult.Errors with unsupported type: []github.com/evanw/esbuild/pkg/api.Message

// skipped field OnLoadResult.Warnings with unsupported type: []github.com/evanw/esbuild/pkg/api.Message

// skipped field OnLoadResult.Contents with unsupported type: *string

@property (nonatomic) NSString* _Nonnull resolveDir;
// skipped field OnLoadResult.Loader with unsupported type: github.com/evanw/esbuild/pkg/api.Loader

// skipped field OnLoadResult.WatchFiles with unsupported type: []string

// skipped field OnLoadResult.WatchDirs with unsupported type: []string

// skipped method OnLoadResult.AddLoadError with unsupported parameter or return types

// skipped method OnLoadResult.AddLoadWarning with unsupported parameter or return types

- (void)addLoadWatchDir:(NSString* _Nullable)dir;
- (void)addLoadWatchFile:(NSString* _Nullable)file;
- (NSString* _Nonnull)getLoadContents;
// skipped method OnLoadResult.GetLoadError with unsupported parameter or return types

- (long)getLoadErrorsCount;
// skipped method OnLoadResult.GetLoadLoader with unsupported parameter or return types

- (NSString* _Nonnull)getLoadPluginName;
- (NSString* _Nonnull)getLoadResolveDir;
// skipped method OnLoadResult.GetLoadWarning with unsupported parameter or return types

- (long)getLoadWarningsCount;
- (NSString* _Nonnull)getLoadWatchDir:(long)index;
- (long)getLoadWatchDirsCount;
- (NSString* _Nonnull)getLoadWatchFile:(long)index;
- (long)getLoadWatchFilesCount;
- (void)setLoadContents:(NSString* _Nullable)contents;
// skipped method OnLoadResult.SetLoadLoader with unsupported parameter or return types

- (void)setLoadPluginName:(NSString* _Nullable)name;
- (void)setLoadResolveDir:(NSString* _Nullable)dir;
@end

/**
 * OnResolveArgs contains arguments passed to the OnResolve callback
 */
@interface EsbuildmobileOnResolveArgs : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull path;
@property (nonatomic) NSString* _Nonnull importer;
@property (nonatomic) NSString* _Nonnull namespace;
@property (nonatomic) NSString* _Nonnull resolveDir;
// skipped field OnResolveArgs.Kind with unsupported type: github.com/Pickleboyonline/ESBuildMobile/lib/esbuildmobile.ResolveKind

@end

/**
 * OnResolveOptions contains options for the OnResolve callback
 */
@interface EsbuildmobileOnResolveOptions : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init;
@property (nonatomic) NSString* _Nonnull filter;
@property (nonatomic) NSString* _Nonnull namespace;
- (NSString* _Nonnull)getResolveFilter;
- (NSString* _Nonnull)getResolveNamespace;
- (void)setResolveFilter:(NSString* _Nullable)filter;
- (void)setResolveNamespace:(NSString* _Nullable)namespace;
// skipped method OnResolveOptions.ToAPI with unsupported parameter or return types

@end

/**
 * OnResolveResult contains the result from an OnResolve callback
 */
@interface EsbuildmobileOnResolveResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init;
@property (nonatomic) NSString* _Nonnull pluginName;
// skipped field OnResolveResult.Errors with unsupported type: []github.com/evanw/esbuild/pkg/api.Message

// skipped field OnResolveResult.Warnings with unsupported type: []github.com/evanw/esbuild/pkg/api.Message

@property (nonatomic) NSString* _Nonnull path;
@property (nonatomic) BOOL external;
// skipped field OnResolveResult.SideEffects with unsupported type: github.com/Pickleboyonline/ESBuildMobile/lib/esbuildmobile.SideEffects

@property (nonatomic) NSString* _Nonnull namespace;
@property (nonatomic) NSString* _Nonnull suffix;
// skipped field OnResolveResult.WatchFiles with unsupported type: []string

// skipped field OnResolveResult.WatchDirs with unsupported type: []string

// skipped method OnResolveResult.AddResolveError with unsupported parameter or return types

// skipped method OnResolveResult.AddResolveWarning with unsupported parameter or return types

- (void)addResolveWatchDir:(NSString* _Nullable)dir;
- (void)addResolveWatchFile:(NSString* _Nullable)file;
// skipped method OnResolveResult.GetResolveError with unsupported parameter or return types

- (long)getResolveErrorsCount;
- (BOOL)getResolveExternal;
- (NSString* _Nonnull)getResolveNamespace;
- (NSString* _Nonnull)getResolvePath;
- (NSString* _Nonnull)getResolvePluginName;
// skipped method OnResolveResult.GetResolveSideEffects with unsupported parameter or return types

- (NSString* _Nonnull)getResolveSuffix;
// skipped method OnResolveResult.GetResolveWarning with unsupported parameter or return types

- (long)getResolveWarningsCount;
- (NSString* _Nonnull)getResolveWatchDir:(long)index;
- (long)getResolveWatchDirsCount;
- (NSString* _Nonnull)getResolveWatchFile:(long)index;
- (long)getResolveWatchFilesCount;
- (void)setResolveExternal:(BOOL)external;
- (void)setResolveNamespace:(NSString* _Nullable)namespace;
- (void)setResolvePath:(NSString* _Nullable)path;
- (void)setResolvePluginName:(NSString* _Nullable)name;
// skipped method OnResolveResult.SetResolveSideEffects with unsupported parameter or return types

- (void)setResolveSuffix:(NSString* _Nullable)suffix;
@end

/**
 * OnStartResult contains the result from an OnStart callback
 */
@interface EsbuildmobileOnStartResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init;
// skipped field OnStartResult.Errors with unsupported type: []github.com/evanw/esbuild/pkg/api.Message

// skipped field OnStartResult.Warnings with unsupported type: []github.com/evanw/esbuild/pkg/api.Message

@end

/**
 * Plugin represents an ESBuild plugin
 */
@interface EsbuildmobilePlugin : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(NSString* _Nullable)name;
- (NSString* _Nonnull)getName;
- (id<EsbuildmobileOnEndCallback> _Nullable)getOnEndCallback;
- (id<EsbuildmobileOnLoadCallback> _Nullable)getOnLoadRuleCallback:(long)index;
- (EsbuildmobileOnLoadOptions* _Nullable)getOnLoadRuleOptions:(long)index;
- (long)getOnLoadRulesCount;
- (id<EsbuildmobileOnResolveCallback> _Nullable)getOnResolveRuleCallback:(long)index;
- (EsbuildmobileOnResolveOptions* _Nullable)getOnResolveRuleOptions:(long)index;
/**
 * Getter methods for rules
 */
- (long)getOnResolveRulesCount;
- (id<EsbuildmobileOnStartCallback> _Nullable)getOnStartCallback;
- (BOOL)hasOnEndCallback;
- (BOOL)hasOnStartCallback;
/**
 * OnEnd sets the end callback
 */
- (void)onEnd:(id<EsbuildmobileOnEndCallback> _Nullable)callback;
/**
 * OnLoad adds a load callback
 */
- (void)onLoad:(EsbuildmobileOnLoadOptions* _Nullable)options callback:(id<EsbuildmobileOnLoadCallback> _Nullable)callback;
/**
 * OnResolve adds a resolve callback
 */
- (void)onResolve:(EsbuildmobileOnResolveOptions* _Nullable)options callback:(id<EsbuildmobileOnResolveCallback> _Nullable)callback;
/**
 * OnStart sets the start callback
 */
- (void)onStart:(id<EsbuildmobileOnStartCallback> _Nullable)callback;
- (void)setPluginName:(NSString* _Nullable)name;
@end

/**
 * ResolveOptions contains options for resolving a module
 */
@interface EsbuildmobileResolveOptions : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull pluginName;
@property (nonatomic) NSString* _Nonnull importer;
@property (nonatomic) NSString* _Nonnull namespace;
@property (nonatomic) NSString* _Nonnull resolveDir;
// skipped field ResolveOptions.Kind with unsupported type: github.com/Pickleboyonline/ESBuildMobile/lib/esbuildmobile.ResolveKind

@end

/**
 * ResolveResult contains the result of resolving a module
 */
@interface EsbuildmobileResolveResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field ResolveResult.Errors with unsupported type: []github.com/evanw/esbuild/pkg/api.Message

// skipped field ResolveResult.Warnings with unsupported type: []github.com/evanw/esbuild/pkg/api.Message

@property (nonatomic) NSString* _Nonnull path;
@property (nonatomic) BOOL external;
@property (nonatomic) BOOL sideEffects;
@property (nonatomic) NSString* _Nonnull namespace;
@property (nonatomic) NSString* _Nonnull suffix;
@end

@interface EsbuildmobileSimpleLoadCallback : NSObject <goSeqRefInterface, EsbuildmobileOnLoadCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull contents;
@property (nonatomic) long loader;
- (EsbuildmobileOnLoadResult* _Nullable)call:(EsbuildmobileOnLoadArgs* _Nullable)args;
@end

/**
 * SimpleOnStartCallback provides a basic implementation for Swift
 */
@interface EsbuildmobileSimpleOnStartCallback : NSObject <goSeqRefInterface, EsbuildmobileOnStartCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewSimpleOnStartCallback creates a simple callback for testing
 */
- (nullable instancetype)init:(NSString* _Nullable)message;
@property (nonatomic) NSString* _Nonnull printMessage;
/**
 * Call implements the OnStartCallback interface
 */
- (EsbuildmobileOnStartResult* _Nullable)call;
@end

/**
 * Simple callback implementations for common use cases
 */
@interface EsbuildmobileSimpleResolveCallback : NSObject <goSeqRefInterface, EsbuildmobileOnResolveCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull path;
@property (nonatomic) NSString* _Nonnull namespace;
@property (nonatomic) BOOL external;
- (EsbuildmobileOnResolveResult* _Nullable)call:(EsbuildmobileOnResolveArgs* _Nullable)args;
@end

/**
 * SwiftOnEndCallback is a concrete implementation that can be used from Swift
 */
@interface EsbuildmobileSwiftOnEndCallback : NSObject <goSeqRefInterface, EsbuildmobileOnEndCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewSwiftOnEndCallback creates a callback that executes a handler
 */
- (nullable instancetype)init;
/**
 * Call implements the OnEndCallback interface
 */
- (EsbuildmobileOnEndResult* _Nullable)call:(EsbuildmobileBuildResult* _Nullable)result;
// skipped method SwiftOnEndCallback.SetHandler with unsupported parameter or return types

@end

/**
 * SwiftOnLoadCallback provides load handling for Swift
 */
@interface EsbuildmobileSwiftOnLoadCallback : NSObject <goSeqRefInterface, EsbuildmobileOnLoadCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewSwiftOnLoadCallback creates a new load callback
 */
- (nullable instancetype)init;
/**
 * Call implements the OnLoadCallback interface
 */
- (EsbuildmobileOnLoadResult* _Nullable)call:(EsbuildmobileOnLoadArgs* _Nullable)args;
// skipped method SwiftOnLoadCallback.SetHandler with unsupported parameter or return types

@end

/**
 * SwiftOnResolveCallback provides resolve handling for Swift
 */
@interface EsbuildmobileSwiftOnResolveCallback : NSObject <goSeqRefInterface, EsbuildmobileOnResolveCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewSwiftOnResolveCallback creates a new resolve callback
 */
- (nullable instancetype)init;
/**
 * Call implements the OnResolveCallback interface
 */
- (EsbuildmobileOnResolveResult* _Nullable)call:(EsbuildmobileOnResolveArgs* _Nullable)args;
// skipped method SwiftOnResolveCallback.SetHandler with unsupported parameter or return types

@end

/**
 * SwiftOnStartCallback is a concrete implementation that can be used from Swift
 */
@interface EsbuildmobileSwiftOnStartCallback : NSObject <goSeqRefInterface, EsbuildmobileOnStartCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewSwiftOnStartCallback creates a callback that executes a simple handler
 */
- (nullable instancetype)init;
/**
 * Call implements the OnStartCallback interface
 */
- (EsbuildmobileOnStartResult* _Nullable)call;
// skipped method SwiftOnStartCallback.SetHandler with unsupported parameter or return types

@end

@interface EsbuildmobileTransformOptions : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewTransformOptions creates a new TransformOptions with default values
 */
- (nullable instancetype)init;
// skipped field TransformOptions.Color with unsupported type: github.com/evanw/esbuild/pkg/api.StderrColor

// skipped field TransformOptions.LogLevel with unsupported type: github.com/evanw/esbuild/pkg/api.LogLevel

@property (nonatomic) long logLimit;
// skipped field TransformOptions.LogOverride with unsupported type: map[string]github.com/evanw/esbuild/pkg/api.LogLevel

// skipped field TransformOptions.Sourcemap with unsupported type: github.com/evanw/esbuild/pkg/api.SourceMap

@property (nonatomic) NSString* _Nonnull sourceRoot;
// skipped field TransformOptions.SourcesContent with unsupported type: github.com/evanw/esbuild/pkg/api.SourcesContent

// skipped field TransformOptions.Target with unsupported type: github.com/evanw/esbuild/pkg/api.Target

// skipped field TransformOptions.Engines with unsupported type: []github.com/evanw/esbuild/pkg/api.Engine

// skipped field TransformOptions.Supported with unsupported type: map[string]bool

// skipped field TransformOptions.Platform with unsupported type: github.com/evanw/esbuild/pkg/api.Platform

// skipped field TransformOptions.Format with unsupported type: github.com/evanw/esbuild/pkg/api.Format

@property (nonatomic) NSString* _Nonnull globalName;
@property (nonatomic) NSString* _Nonnull mangleProps;
@property (nonatomic) NSString* _Nonnull reserveProps;
// skipped field TransformOptions.MangleQuoted with unsupported type: github.com/evanw/esbuild/pkg/api.MangleQuoted

// skipped field TransformOptions.MangleCache with unsupported type: map[string]interface{}

// skipped field TransformOptions.Drop with unsupported type: github.com/evanw/esbuild/pkg/api.Drop

// skipped field TransformOptions.DropLabels with unsupported type: []string

@property (nonatomic) BOOL minifyWhitespace;
@property (nonatomic) BOOL minifyIdentifiers;
@property (nonatomic) BOOL minifySyntax;
@property (nonatomic) long lineLimit;
// skipped field TransformOptions.Charset with unsupported type: github.com/evanw/esbuild/pkg/api.Charset

// skipped field TransformOptions.TreeShaking with unsupported type: github.com/evanw/esbuild/pkg/api.TreeShaking

@property (nonatomic) BOOL ignoreAnnotations;
// skipped field TransformOptions.LegalComments with unsupported type: github.com/evanw/esbuild/pkg/api.LegalComments

// skipped field TransformOptions.JSX with unsupported type: github.com/evanw/esbuild/pkg/api.JSX

@property (nonatomic) NSString* _Nonnull jsxFactory;
@property (nonatomic) NSString* _Nonnull jsxFragment;
@property (nonatomic) NSString* _Nonnull jsxImportSource;
@property (nonatomic) BOOL jsxDev;
@property (nonatomic) BOOL jsxSideEffects;
@property (nonatomic) NSString* _Nonnull tsconfigRaw;
@property (nonatomic) NSString* _Nonnull banner;
@property (nonatomic) NSString* _Nonnull footer;
// skipped field TransformOptions.Define with unsupported type: map[string]string

// skipped field TransformOptions.Pure with unsupported type: []string

@property (nonatomic) BOOL keepNames;
@property (nonatomic) NSString* _Nonnull sourcefile;
// skipped field TransformOptions.Loader with unsupported type: github.com/evanw/esbuild/pkg/api.Loader

- (void)addDropLabel:(NSString* _Nullable)label;
- (void)addEngine:(NSString* _Nullable)name version:(NSString* _Nullable)version;
/**
 * Array manipulation methods
 */
- (void)addPure:(NSString* _Nullable)fn;
- (void)clearDefine;
- (void)clearDropLabels;
/**
 * Clear methods for arrays and maps
 */
- (void)clearEngines;
- (void)clearLogOverride;
- (void)clearMangleCache;
- (void)clearPure;
- (void)clearSupported;
/**
 * Configure banner text
 */
- (void)configureBanner:(NSString* _Nullable)banner;
// skipped method TransformOptions.ConfigureCharset with unsupported parameter or return types

/**
 * Configure charset by string
 */
- (void)configureCharsetByString:(NSString* _Nullable)charset;
// skipped method TransformOptions.ConfigureColor with unsupported parameter or return types

/**
 * Configure color by string
 */
- (void)configureColorByString:(NSString* _Nullable)color;
// skipped method TransformOptions.ConfigureDefine with unsupported parameter or return types

/**
 * Configure define by key-value pairs
 */
- (void)configureDefineEntry:(NSString* _Nullable)key value:(NSString* _Nullable)value;
// skipped method TransformOptions.ConfigureDrop with unsupported parameter or return types

/**
 * Configure drop by string
 */
- (void)configureDropByString:(NSString* _Nullable)drop;
// skipped method TransformOptions.ConfigureDropLabels with unsupported parameter or return types

// skipped method TransformOptions.ConfigureDropLabelsBySlice with unsupported parameter or return types

// skipped method TransformOptions.ConfigureEngines with unsupported parameter or return types

/**
 * Configure footer text
 */
- (void)configureFooter:(NSString* _Nullable)footer;
// skipped method TransformOptions.ConfigureFormat with unsupported parameter or return types

/**
 * Configure format by string
 */
- (void)configureFormatByString:(NSString* _Nullable)format;
/**
 * Configure global name for UMD bundles
 */
- (void)configureGlobalName:(NSString* _Nullable)name;
/**
 * Configure ignore annotations
 */
- (void)configureIgnoreAnnotations:(BOOL)enabled;
// skipped method TransformOptions.ConfigureJSX with unsupported parameter or return types

/**
 * Configure JSX mode by string
 */
- (void)configureJSXByString:(NSString* _Nullable)jsx;
/**
 * Configure JSX development mode
 */
- (void)configureJSXDev:(BOOL)enabled;
/**
 * Change `React.createElement` to custom name
 */
- (void)configureJSXFactory:(NSString* _Nullable)factoryName;
/**
 * Change `React.Fragment` to custom name
 */
- (void)configureJSXFragment:(NSString* _Nullable)fragmentName;
/**
 * Configure JSX import source
 */
- (void)configureJSXImportSource:(NSString* _Nullable)importSource;
/**
 * Configure JSX side effects
 */
- (void)configureJSXSideEffects:(BOOL)enabled;
/**
 * Configure keep names option
 */
- (void)configureKeepNames:(BOOL)enabled;
// skipped method TransformOptions.ConfigureLegalComments with unsupported parameter or return types

/**
 * Configure legal comments by string
 */
- (void)configureLegalCommentsByString:(NSString* _Nullable)comments;
/**
 * Configure line limit
 */
- (void)configureLineLimit:(long)limit;
// skipped method TransformOptions.ConfigureLoader with unsupported parameter or return types

/**
 * Configure loader by string
 */
- (void)configureLoaderByString:(NSString* _Nullable)loader;
// skipped method TransformOptions.ConfigureLogLevel with unsupported parameter or return types

/**
 * Configure log level by string
 */
- (void)configureLogLevelByString:(NSString* _Nullable)level;
/**
 * Configure log limit
 */
- (void)configureLogLimit:(long)limit;
// skipped method TransformOptions.ConfigureLogOverride with unsupported parameter or return types

// skipped method TransformOptions.ConfigureMangleCache with unsupported parameter or return types

/**
 * Configure mangle properties pattern
 */
- (void)configureMangleProps:(NSString* _Nullable)pattern;
// skipped method TransformOptions.ConfigureMangleQuoted with unsupported parameter or return types

/**
 * Configure mangle quoted by string
 */
- (void)configureMangleQuotedByString:(NSString* _Nullable)quoted;
/**
 * Configure identifier minification
 */
- (void)configureMinifyIdentifiers:(BOOL)enabled;
/**
 * Configure syntax minification
 */
- (void)configureMinifySyntax:(BOOL)enabled;
/**
 * Configure whitespace minification
 */
- (void)configureMinifyWhitespace:(BOOL)enabled;
// skipped method TransformOptions.ConfigurePlatform with unsupported parameter or return types

/**
 * Configure platform by string
 */
- (void)configurePlatformByString:(NSString* _Nullable)platform;
// skipped method TransformOptions.ConfigurePure with unsupported parameter or return types

// skipped method TransformOptions.ConfigurePureBySlice with unsupported parameter or return types

/**
 * Configure reserve properties pattern
 */
- (void)configureReserveProps:(NSString* _Nullable)pattern;
/**
 * Configure source root directory
 */
- (void)configureSourceRoot:(NSString* _Nullable)root;
/**
 * Configure source file name
 */
- (void)configureSourcefile:(NSString* _Nullable)filename;
// skipped method TransformOptions.ConfigureSourcemap with unsupported parameter or return types

/**
 * Configure sourcemap by string
 */
- (void)configureSourcemapByString:(NSString* _Nullable)sourcemap;
// skipped method TransformOptions.ConfigureSourcesContent with unsupported parameter or return types

/**
 * Configure sources content by string
 */
- (void)configureSourcesContentByString:(NSString* _Nullable)content;
// skipped method TransformOptions.ConfigureSupported with unsupported parameter or return types

/**
 * Configure supported feature
 */
- (void)configureSupportedFeature:(NSString* _Nullable)feature supported:(BOOL)supported;
// skipped method TransformOptions.ConfigureTarget with unsupported parameter or return types

/**
 * Configure target by string
 */
- (void)configureTargetByString:(NSString* _Nullable)target;
// skipped method TransformOptions.ConfigureTreeShaking with unsupported parameter or return types

/**
 * Configure tree shaking by string
 */
- (void)configureTreeShakingByString:(NSString* _Nullable)shaking;
/**
 * Configure raw tsconfig content
 */
- (void)configureTsconfigRaw:(NSString* _Nullable)config;
- (long)getCharset;
- (long)getColor;
/**
 * Getter methods for map sizes
 */
- (long)getDefineCount;
/**
 * Individual key getter methods (since slices aren't supported by gomobile)
 */
- (NSString* _Nonnull)getDefineKey:(long)index;
/**
 * Methods to get values from maps by key
 */
- (NSString* _Nonnull)getDefineValue:(NSString* _Nullable)key;
- (long)getDrop;
- (NSString* _Nonnull)getDropLabel:(long)index;
- (long)getDropLabelsCount;
/**
 * Getter methods for slices and maps (return length/size info)
 */
- (long)getEnginesCount;
- (long)getFormat;
- (long)getJSX;
- (long)getLegalComments;
- (long)getLoader;
- (long)getLogLevel;
- (long)getLogOverrideCount;
- (NSString* _Nonnull)getLogOverrideKey:(long)index;
- (long)getLogOverrideValue:(NSString* _Nullable)key;
- (long)getMangleCacheCount;
- (long)getMangleQuoted;
/**
 * Getter methods for current TransformOptions values
 */
- (long)getPlatform;
/**
 * Getter methods for string array elements
 */
- (NSString* _Nonnull)getPure:(long)index;
- (long)getPureCount;
- (long)getSourcemap;
- (long)getSourcesContent;
- (long)getSupportedCount;
- (NSString* _Nonnull)getSupportedKey:(long)index;
- (BOOL)getSupportedValue:(NSString* _Nullable)key;
- (long)getTarget;
- (long)getTreeShaking;
- (void)setCharsetByInt:(long)charset;
- (void)setColorByInt:(long)color;
- (void)setDropByInt:(long)drop;
- (void)setFormatByInt:(long)format;
- (void)setJSXByInt:(long)jsx;
- (void)setLegalCommentsByInt:(long)comments;
- (void)setLoaderByInt:(long)loader;
- (void)setLogLevelByInt:(long)logLevel;
/**
 * Methods to set map values by key with integer enum values
 */
- (void)setLogOverrideValueByInt:(NSString* _Nullable)key value:(long)value;
- (void)setMangleQuotedByInt:(long)quoted;
/**
 * Set methods using enum values as integers
 */
- (void)setPlatformByInt:(long)platform;
- (void)setSourcemapByInt:(long)sourcemap;
- (void)setSourcesContentByInt:(long)content;
- (void)setTargetByInt:(long)target;
- (void)setTreeShakingByInt:(long)shaking;
/**
 * WithJSXFactory sets the JSX factory function name (e.g., "React.createElement")
 */
- (void)withJSXFactory:(NSString* _Nullable)factoryName;
/**
 * WithJSXFragment sets the JSX fragment function name (e.g., "React.Fragment")
 */
- (void)withJSXFragment:(NSString* _Nullable)fragmentName;
@end

/**
 * Common filter pattern constants
 */
FOUNDATION_EXPORT NSString* _Nonnull const EsbuildmobileFilterAbsoluteImports;
/**
 * Common filter pattern constants
 */
FOUNDATION_EXPORT NSString* _Nonnull const EsbuildmobileFilterAllFiles;
/**
 * Common filter pattern constants
 */
FOUNDATION_EXPORT NSString* _Nonnull const EsbuildmobileFilterCSSFiles;
/**
 * Common filter pattern constants
 */
FOUNDATION_EXPORT NSString* _Nonnull const EsbuildmobileFilterFontFiles;
/**
 * Common filter pattern constants
 */
FOUNDATION_EXPORT NSString* _Nonnull const EsbuildmobileFilterImageFiles;
/**
 * Common filter pattern constants
 */
FOUNDATION_EXPORT NSString* _Nonnull const EsbuildmobileFilterJQuery;
/**
 * Common filter pattern constants
 */
FOUNDATION_EXPORT NSString* _Nonnull const EsbuildmobileFilterJSFiles;
/**
 * Common filter pattern constants
 */
FOUNDATION_EXPORT NSString* _Nonnull const EsbuildmobileFilterJSONFiles;
/**
 * Common filter pattern constants
 */
FOUNDATION_EXPORT NSString* _Nonnull const EsbuildmobileFilterLESSFiles;
/**
 * Common filter pattern constants
 */
FOUNDATION_EXPORT NSString* _Nonnull const EsbuildmobileFilterLodash;
/**
 * Common filter pattern constants
 */
FOUNDATION_EXPORT NSString* _Nonnull const EsbuildmobileFilterNodeModules;
/**
 * Common filter pattern constants
 */
FOUNDATION_EXPORT NSString* _Nonnull const EsbuildmobileFilterReact;
/**
 * Common filter pattern constants
 */
FOUNDATION_EXPORT NSString* _Nonnull const EsbuildmobileFilterReactDOM;
/**
 * Common filter pattern constants
 */
FOUNDATION_EXPORT NSString* _Nonnull const EsbuildmobileFilterRelativeImports;
/**
 * Common filter pattern constants
 */
FOUNDATION_EXPORT NSString* _Nonnull const EsbuildmobileFilterSCSSFiles;
/**
 * Common filter pattern constants
 */
FOUNDATION_EXPORT NSString* _Nonnull const EsbuildmobileFilterTSFiles;
/**
 * Common namespace constants
 */
FOUNDATION_EXPORT NSString* _Nonnull const EsbuildmobileNamespaceExternal;
/**
 * Common namespace constants
 */
FOUNDATION_EXPORT NSString* _Nonnull const EsbuildmobileNamespaceFile;
/**
 * Common namespace constants
 */
FOUNDATION_EXPORT NSString* _Nonnull const EsbuildmobileNamespaceGenerated;
/**
 * Common namespace constants
 */
FOUNDATION_EXPORT NSString* _Nonnull const EsbuildmobileNamespaceHTTP;
/**
 * Common namespace constants
 */
FOUNDATION_EXPORT NSString* _Nonnull const EsbuildmobileNamespaceHTTPS;
/**
 * Common namespace constants
 */
FOUNDATION_EXPORT NSString* _Nonnull const EsbuildmobileNamespaceTransformed;
/**
 * Common namespace constants
 */
FOUNDATION_EXPORT NSString* _Nonnull const EsbuildmobileNamespaceVirtual;
// skipped const ResolveCSSComposesFrom with unsupported type: github.com/Pickleboyonline/ESBuildMobile/lib/esbuildmobile.ResolveKind

// skipped const ResolveCSSImportRule with unsupported type: github.com/Pickleboyonline/ESBuildMobile/lib/esbuildmobile.ResolveKind

// skipped const ResolveCSSURLToken with unsupported type: github.com/Pickleboyonline/ESBuildMobile/lib/esbuildmobile.ResolveKind

// skipped const ResolveEntryPoint with unsupported type: github.com/Pickleboyonline/ESBuildMobile/lib/esbuildmobile.ResolveKind

// skipped const ResolveJSDynamicImport with unsupported type: github.com/Pickleboyonline/ESBuildMobile/lib/esbuildmobile.ResolveKind

// skipped const ResolveJSImportStatement with unsupported type: github.com/Pickleboyonline/ESBuildMobile/lib/esbuildmobile.ResolveKind

// skipped const ResolveJSRequireCall with unsupported type: github.com/Pickleboyonline/ESBuildMobile/lib/esbuildmobile.ResolveKind

// skipped const ResolveJSRequireResolve with unsupported type: github.com/Pickleboyonline/ESBuildMobile/lib/esbuildmobile.ResolveKind

// skipped const ResolveNone with unsupported type: github.com/Pickleboyonline/ESBuildMobile/lib/esbuildmobile.ResolveKind

// skipped const SideEffectsFalse with unsupported type: github.com/Pickleboyonline/ESBuildMobile/lib/esbuildmobile.SideEffects

// skipped const SideEffectsTrue with unsupported type: github.com/Pickleboyonline/ESBuildMobile/lib/esbuildmobile.SideEffects


/**
 * Build compiles JavaScript using esbuild's build API with stdin.
Returns the bundled code as a string if Write is false.
`BuildOptions` is optional.
 */
FOUNDATION_EXPORT NSString* _Nonnull EsbuildmobileBuild(NSString* _Nullable input, EsbuildmobileBuildOptions* _Nullable options, NSError* _Nullable* _Nullable error);

/**
 * CreateCSSLoadResult creates a load result with CSS loader
 */
FOUNDATION_EXPORT EsbuildmobileOnLoadResult* _Nullable EsbuildmobileCreateCSSLoadResult(NSString* _Nullable contents);

/**
 * CreateExternalResolveResult creates a resolve result that marks the import as external
 */
FOUNDATION_EXPORT EsbuildmobileOnResolveResult* _Nullable EsbuildmobileCreateExternalResolveResult(NSString* _Nullable path);

/**
 * CreateFilterForNamespace creates an OnLoadOptions with a namespace filter
 */
FOUNDATION_EXPORT EsbuildmobileOnLoadOptions* _Nullable EsbuildmobileCreateFilterForNamespace(NSString* _Nullable namespace);

/**
 * CreateFilterForPath creates an OnResolveOptions with a path filter
 */
FOUNDATION_EXPORT EsbuildmobileOnResolveOptions* _Nullable EsbuildmobileCreateFilterForPath(NSString* _Nullable pathPattern);

/**
 * CreateFilterForPathAndNamespace creates an OnResolveOptions with both path and namespace filters
 */
FOUNDATION_EXPORT EsbuildmobileOnResolveOptions* _Nullable EsbuildmobileCreateFilterForPathAndNamespace(NSString* _Nullable pathPattern, NSString* _Nullable namespace);

/**
 * CreateJSLoadResult creates a load result with JS loader
 */
FOUNDATION_EXPORT EsbuildmobileOnLoadResult* _Nullable EsbuildmobileCreateJSLoadResult(NSString* _Nullable contents);

/**
 * CreateJSONLoadResult creates a load result with JSON loader
 */
FOUNDATION_EXPORT EsbuildmobileOnLoadResult* _Nullable EsbuildmobileCreateJSONLoadResult(NSString* _Nullable contents);

// skipped function CreateLoadResult with unsupported parameter or return types


// skipped function CreateLoadResultWithResolveDir with unsupported parameter or return types


/**
 * CreateNamespaceResolveResult creates a resolve result that redirects to a specific namespace
 */
FOUNDATION_EXPORT EsbuildmobileOnResolveResult* _Nullable EsbuildmobileCreateNamespaceResolveResult(NSString* _Nullable path, NSString* _Nullable namespace);

/**
 * CreateResolveResult creates a basic resolve result
 */
FOUNDATION_EXPORT EsbuildmobileOnResolveResult* _Nullable EsbuildmobileCreateResolveResult(NSString* _Nullable path, BOOL external, NSString* _Nullable namespace);

// skipped function CreateSimpleTransformPlugin with unsupported parameter or return types


/**
 * CreateTSLoadResult creates a load result with TypeScript loader
 */
FOUNDATION_EXPORT EsbuildmobileOnLoadResult* _Nullable EsbuildmobileCreateTSLoadResult(NSString* _Nullable contents);

/**
 * CreateTextLoadResult creates a load result with text loader
 */
FOUNDATION_EXPORT EsbuildmobileOnLoadResult* _Nullable EsbuildmobileCreateTextLoadResult(NSString* _Nullable contents);

// skipped function EngineNameFromString with unsupported parameter or return types


// skipped function EngineNameToString with unsupported parameter or return types


// skipped function FromAPIEngine with unsupported parameter or return types


FOUNDATION_EXPORT long EsbuildmobileGetCharsetASCII(void);

/**
 * Charset enum values
 */
FOUNDATION_EXPORT long EsbuildmobileGetCharsetDefault(void);

FOUNDATION_EXPORT long EsbuildmobileGetCharsetUTF8(void);

FOUNDATION_EXPORT long EsbuildmobileGetColorAlways(void);

/**
 * StderrColor enum values
 */
FOUNDATION_EXPORT long EsbuildmobileGetColorIfTerminal(void);

FOUNDATION_EXPORT long EsbuildmobileGetColorNever(void);

/**
 * Drop enum values (these are flags, so they can be combined)
 */
FOUNDATION_EXPORT long EsbuildmobileGetDropConsole(void);

FOUNDATION_EXPORT long EsbuildmobileGetDropDebugger(void);

/**
 * Engine name constant getters for mobile bindings
 */
FOUNDATION_EXPORT long EsbuildmobileGetEngineChrome(void);

FOUNDATION_EXPORT long EsbuildmobileGetEngineDeno(void);

FOUNDATION_EXPORT long EsbuildmobileGetEngineEdge(void);

FOUNDATION_EXPORT long EsbuildmobileGetEngineFirefox(void);

FOUNDATION_EXPORT long EsbuildmobileGetEngineHermes(void);

FOUNDATION_EXPORT long EsbuildmobileGetEngineIE(void);

FOUNDATION_EXPORT long EsbuildmobileGetEngineIOS(void);

FOUNDATION_EXPORT long EsbuildmobileGetEngineNode(void);

FOUNDATION_EXPORT long EsbuildmobileGetEngineOpera(void);

FOUNDATION_EXPORT long EsbuildmobileGetEngineRhino(void);

FOUNDATION_EXPORT long EsbuildmobileGetEngineSafari(void);

FOUNDATION_EXPORT long EsbuildmobileGetFormatCommonJS(void);

/**
 * Format enum values
 */
FOUNDATION_EXPORT long EsbuildmobileGetFormatDefault(void);

FOUNDATION_EXPORT long EsbuildmobileGetFormatESModule(void);

FOUNDATION_EXPORT long EsbuildmobileGetFormatIIFE(void);

FOUNDATION_EXPORT long EsbuildmobileGetJSXAutomatic(void);

FOUNDATION_EXPORT long EsbuildmobileGetJSXPreserve(void);

/**
 * JSX enum values
 */
FOUNDATION_EXPORT long EsbuildmobileGetJSXTransform(void);

/**
 * LegalComments enum values
 */
FOUNDATION_EXPORT long EsbuildmobileGetLegalCommentsDefault(void);

FOUNDATION_EXPORT long EsbuildmobileGetLegalCommentsEndOfFile(void);

FOUNDATION_EXPORT long EsbuildmobileGetLegalCommentsExternal(void);

FOUNDATION_EXPORT long EsbuildmobileGetLegalCommentsInline(void);

FOUNDATION_EXPORT long EsbuildmobileGetLegalCommentsLinked(void);

FOUNDATION_EXPORT long EsbuildmobileGetLegalCommentsNone(void);

FOUNDATION_EXPORT long EsbuildmobileGetLoaderBase64(void);

FOUNDATION_EXPORT long EsbuildmobileGetLoaderBinary(void);

FOUNDATION_EXPORT long EsbuildmobileGetLoaderCSS(void);

FOUNDATION_EXPORT long EsbuildmobileGetLoaderCopy(void);

FOUNDATION_EXPORT long EsbuildmobileGetLoaderDataURL(void);

FOUNDATION_EXPORT long EsbuildmobileGetLoaderDefault(void);

FOUNDATION_EXPORT long EsbuildmobileGetLoaderEmpty(void);

FOUNDATION_EXPORT long EsbuildmobileGetLoaderFile(void);

FOUNDATION_EXPORT long EsbuildmobileGetLoaderGlobalCSS(void);

FOUNDATION_EXPORT long EsbuildmobileGetLoaderJS(void);

FOUNDATION_EXPORT long EsbuildmobileGetLoaderJSON(void);

FOUNDATION_EXPORT long EsbuildmobileGetLoaderJSX(void);

FOUNDATION_EXPORT long EsbuildmobileGetLoaderLocalCSS(void);

/**
 * Loader enum values
 */
FOUNDATION_EXPORT long EsbuildmobileGetLoaderNone(void);

FOUNDATION_EXPORT long EsbuildmobileGetLoaderTS(void);

FOUNDATION_EXPORT long EsbuildmobileGetLoaderTSX(void);

FOUNDATION_EXPORT long EsbuildmobileGetLoaderText(void);

FOUNDATION_EXPORT long EsbuildmobileGetLogLevelDebug(void);

FOUNDATION_EXPORT long EsbuildmobileGetLogLevelError(void);

FOUNDATION_EXPORT long EsbuildmobileGetLogLevelInfo(void);

/**
 * LogLevel enum values
 */
FOUNDATION_EXPORT long EsbuildmobileGetLogLevelSilent(void);

FOUNDATION_EXPORT long EsbuildmobileGetLogLevelVerbose(void);

FOUNDATION_EXPORT long EsbuildmobileGetLogLevelWarning(void);

/**
 * MangleQuoted enum values
 */
FOUNDATION_EXPORT long EsbuildmobileGetMangleQuotedFalse(void);

FOUNDATION_EXPORT long EsbuildmobileGetMangleQuotedTrue(void);

FOUNDATION_EXPORT long EsbuildmobileGetPackagesBundle(void);

/**
 * Packages enum values
 */
FOUNDATION_EXPORT long EsbuildmobileGetPackagesDefault(void);

FOUNDATION_EXPORT long EsbuildmobileGetPackagesExternal(void);

FOUNDATION_EXPORT long EsbuildmobileGetPlatformBrowser(void);

/**
 * Platform enum values
 */
FOUNDATION_EXPORT long EsbuildmobileGetPlatformDefault(void);

FOUNDATION_EXPORT long EsbuildmobileGetPlatformNeutral(void);

FOUNDATION_EXPORT long EsbuildmobileGetPlatformNode(void);

// skipped function GetResolveCSSComposesFrom with unsupported parameter or return types


// skipped function GetResolveCSSImportRule with unsupported parameter or return types


// skipped function GetResolveCSSURLToken with unsupported parameter or return types


// skipped function GetResolveEntryPoint with unsupported parameter or return types


// skipped function GetResolveJSDynamicImport with unsupported parameter or return types


// skipped function GetResolveJSImportStatement with unsupported parameter or return types


// skipped function GetResolveJSRequireCall with unsupported parameter or return types


// skipped function GetResolveJSRequireResolve with unsupported parameter or return types


// skipped function GetResolveNone with unsupported parameter or return types


// skipped function GetSideEffectsFalse with unsupported parameter or return types


// skipped function GetSideEffectsTrue with unsupported parameter or return types


FOUNDATION_EXPORT long EsbuildmobileGetSourceMapExternal(void);

FOUNDATION_EXPORT long EsbuildmobileGetSourceMapInline(void);

FOUNDATION_EXPORT long EsbuildmobileGetSourceMapInlineAndExternal(void);

FOUNDATION_EXPORT long EsbuildmobileGetSourceMapLinked(void);

/**
 * SourceMap enum values
 */
FOUNDATION_EXPORT long EsbuildmobileGetSourceMapNone(void);

FOUNDATION_EXPORT long EsbuildmobileGetSourcesContentExclude(void);

/**
 * SourcesContent enum values
 */
FOUNDATION_EXPORT long EsbuildmobileGetSourcesContentInclude(void);

/**
 * Target enum values
 */
FOUNDATION_EXPORT long EsbuildmobileGetTargetDefault(void);

FOUNDATION_EXPORT long EsbuildmobileGetTargetES2015(void);

FOUNDATION_EXPORT long EsbuildmobileGetTargetES2016(void);

FOUNDATION_EXPORT long EsbuildmobileGetTargetES2017(void);

FOUNDATION_EXPORT long EsbuildmobileGetTargetES2018(void);

FOUNDATION_EXPORT long EsbuildmobileGetTargetES2019(void);

FOUNDATION_EXPORT long EsbuildmobileGetTargetES2020(void);

FOUNDATION_EXPORT long EsbuildmobileGetTargetES2021(void);

FOUNDATION_EXPORT long EsbuildmobileGetTargetES2022(void);

FOUNDATION_EXPORT long EsbuildmobileGetTargetES2023(void);

FOUNDATION_EXPORT long EsbuildmobileGetTargetES2024(void);

FOUNDATION_EXPORT long EsbuildmobileGetTargetES5(void);

FOUNDATION_EXPORT long EsbuildmobileGetTargetESNext(void);

/**
 * TreeShaking enum values
 */
FOUNDATION_EXPORT long EsbuildmobileGetTreeShakingDefault(void);

FOUNDATION_EXPORT long EsbuildmobileGetTreeShakingFalse(void);

FOUNDATION_EXPORT long EsbuildmobileGetTreeShakingTrue(void);

/**
 * NewBuildOptions returns BuildOptions with defaults
 */
FOUNDATION_EXPORT EsbuildmobileBuildOptions* _Nullable EsbuildmobileNewBuildOptions(void);

FOUNDATION_EXPORT EsbuildmobileOnEndResult* _Nullable EsbuildmobileNewOnEndResult(void);

FOUNDATION_EXPORT EsbuildmobileOnLoadOptions* _Nullable EsbuildmobileNewOnLoadOptions(void);

FOUNDATION_EXPORT EsbuildmobileOnLoadResult* _Nullable EsbuildmobileNewOnLoadResult(void);

FOUNDATION_EXPORT EsbuildmobileOnResolveOptions* _Nullable EsbuildmobileNewOnResolveOptions(void);

FOUNDATION_EXPORT EsbuildmobileOnResolveResult* _Nullable EsbuildmobileNewOnResolveResult(void);

FOUNDATION_EXPORT EsbuildmobileOnStartResult* _Nullable EsbuildmobileNewOnStartResult(void);

FOUNDATION_EXPORT EsbuildmobilePlugin* _Nullable EsbuildmobileNewPlugin(NSString* _Nullable name);

/**
 * NewSimpleOnStartCallback creates a simple callback for testing
 */
FOUNDATION_EXPORT EsbuildmobileSimpleOnStartCallback* _Nullable EsbuildmobileNewSimpleOnStartCallback(NSString* _Nullable message);

/**
 * NewSwiftOnEndCallback creates a callback that executes a handler
 */
FOUNDATION_EXPORT EsbuildmobileSwiftOnEndCallback* _Nullable EsbuildmobileNewSwiftOnEndCallback(void);

/**
 * NewSwiftOnLoadCallback creates a new load callback
 */
FOUNDATION_EXPORT EsbuildmobileSwiftOnLoadCallback* _Nullable EsbuildmobileNewSwiftOnLoadCallback(void);

/**
 * NewSwiftOnResolveCallback creates a new resolve callback
 */
FOUNDATION_EXPORT EsbuildmobileSwiftOnResolveCallback* _Nullable EsbuildmobileNewSwiftOnResolveCallback(void);

/**
 * NewSwiftOnStartCallback creates a callback that executes a simple handler
 */
FOUNDATION_EXPORT EsbuildmobileSwiftOnStartCallback* _Nullable EsbuildmobileNewSwiftOnStartCallback(void);

/**
 * NewTransformOptions creates a new TransformOptions with default values
 */
FOUNDATION_EXPORT EsbuildmobileTransformOptions* _Nullable EsbuildmobileNewTransformOptions(void);

// skipped function OnLoadOptionsFromAPI with unsupported parameter or return types


// skipped function OnResolveOptionsFromAPI with unsupported parameter or return types


// skipped function ResolveKindFromAPI with unsupported parameter or return types


// skipped function SideEffectsFromAPI with unsupported parameter or return types


/**
 * Returns code and error
`TransformOptions` is optional
 */
FOUNDATION_EXPORT NSString* _Nonnull EsbuildmobileTransformJSX(NSString* _Nullable input, EsbuildmobileTransformOptions* _Nullable options, NSError* _Nullable* _Nullable error);

@class EsbuildmobileOnEndCallback;

@class EsbuildmobileOnLoadCallback;

@class EsbuildmobileOnResolveCallback;

@class EsbuildmobileOnStartCallback;

@interface EsbuildmobileOnEndCallback : NSObject <goSeqRefInterface, EsbuildmobileOnEndCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (EsbuildmobileOnEndResult* _Nullable)call:(EsbuildmobileBuildResult* _Nullable)result;
@end

@interface EsbuildmobileOnLoadCallback : NSObject <goSeqRefInterface, EsbuildmobileOnLoadCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (EsbuildmobileOnLoadResult* _Nullable)call:(EsbuildmobileOnLoadArgs* _Nullable)args;
@end

/**
 * Callback interfaces for mobile compatibility
 */
@interface EsbuildmobileOnResolveCallback : NSObject <goSeqRefInterface, EsbuildmobileOnResolveCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (EsbuildmobileOnResolveResult* _Nullable)call:(EsbuildmobileOnResolveArgs* _Nullable)args;
@end

@interface EsbuildmobileOnStartCallback : NSObject <goSeqRefInterface, EsbuildmobileOnStartCallback> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (EsbuildmobileOnStartResult* _Nullable)call;
@end

#endif
