
// Objective-C API for talking to the following Go packages
//
//	github.com/Pickleboyonline/ESBuildMobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __ESBuildMobile_FRAMEWORK_H__
#define __ESBuildMobile_FRAMEWORK_H__

#include "Esbuildmobile.objc.h"
#include "Universe.objc.h"

#endif
